version: '3'

services:

  nginx:
    build: ./nginx
    container_name: deploybase.nginx
    ports:
      - "8888:8888"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./api/static:/static
    depends_on:
      - backend
    restart: always

  backend:
    build: ./api
    container_name: deploybase.backend
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - 8001:8001
    environment:
      - PORT=8001
      - DJANGO_SETTINGS_MODULE=main.settings_development
    volumes:
      - ./api:/opt/backend
    restart: always